import os
import argparse
from typing import List, Tuple

import numpy as np


def _load_change_ratios(data_dir: str, sims_list: List[int]) -> Tuple[np.ndarray, np.ndarray]:
    sims = np.asarray(sims_list, dtype=np.int32)
    ratios = []
    for s in sims:
        path = os.path.join(data_dir, f"robust_vs_baseline_sims{s}.npz")
        if not os.path.exists(path):
            raise FileNotFoundError(f"Missing data file for sims={s}: {path}")
        data = np.load(path)
        changed = np.asarray(data["changed"], dtype=bool)
        if changed.size == 0:
            ratios.append(float("nan"))
        else:
            ratios.append(float(changed.astype(np.float64).mean()))
    return sims, np.asarray(ratios, dtype=np.float64)


def main():
    ap = argparse.ArgumentParser(
        description=(
            "Plot action-change ratio vs sims, using data generated by "
            "gen_robust_baseline_data.py."
        )
    )
    ap.add_argument(
        "--data-dir",
        type=str,
        default="./robust_vs_baseline_data",
        help="Directory containing robust_vs_baseline_sims*.npz files.",
    )
    ap.add_argument(
        "--sims",
        type=int,
        nargs="+",
        default=[25, 50, 100, 200],
        help="List of sims values to include on the x-axis.",
    )
    ap.add_argument(
        "--out-path",
        type=str,
        default="./robust_vs_baseline_change_ratio.png",
        help="Output path for the line plot PNG.",
    )
    args = ap.parse_args()

    sims, ratios = _load_change_ratios(args.data_dir, args.sims)

    # If matplotlib is unavailable, fall back to console output only.
    try:
        import matplotlib.pyplot as plt
    except Exception:
        print("Matplotlib not available; skipping plot.", flush=True)
        print("sims:", list(map(int, sims)), flush=True)
        print("action_change_ratio:", [float(r) for r in ratios], flush=True)
        return

    plt.figure(figsize=(6, 3.8))
    plt.plot(sims, ratios, marker="o", color="#4e79a7")
    plt.xlabel("MCTS sims")
    plt.ylabel("Action change ratio (robust vs baseline)")
    plt.title("Action change ratio vs MCTS sims")
    plt.ylim(0.0, 1.0)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()

    out_dir = os.path.dirname(args.out_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    plt.savefig(args.out_path, dpi=600)
    plt.close()

    print("sims:", list(map(int, sims)), flush=True)
    print("action_change_ratio:", [f"{r:.4f}" for r in ratios], flush=True)
    print(f"Saved line plot to: {args.out_path}", flush=True)


if __name__ == "__main__":
    main()

